---
name: Quality assurance
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 7.4]
        laravel: [^8.0, ^7.0]
        include:
          - laravel: ^8.0
            testbench: ^6.0
          - laravel: ^7.0
            testbench: ^5.0
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/*.clover:clover
          debug: true

      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1
        if: ${{ matrix.php == '7.4' }}
